package com.gaia.member.androidlib;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table BOOK_LIB.
 */
public class BookLib {

    private Long id;
    private String name;
    private Integer price;
    private String type;
    private String publish_date;

    public BookLib() {
    }

    public BookLib(Long id) {
        this.id = id;
    }

    public BookLib(Long id, String name, Integer price, String type, String publish_date) {
        this.id = id;
        this.name = name;
        this.price = price;
        this.type = type;
        this.publish_date = publish_date;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Integer getPrice() {
        return price;
    }

    public void setPrice(Integer price) {
        this.price = price;
    }

    public String getType() {
        return type;
    }

    public void setType(String type) {
        this.type = type;
    }

    public String getPublish_date() {
        return publish_date;
    }

    public void setPublish_date(String publish_date) {
        this.publish_date = publish_date;
    }

}
