package com.gaia.member.androidlib;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig noteDaoConfig;
    private final DaoConfig bookLibDaoConfig;
    private final DaoConfig studentDaoConfig;
    private final DaoConfig stepsDaoConfig;

    private final NoteDao noteDao;
    private final BookLibDao bookLibDao;
    private final StudentDao studentDao;
    private final StepsDao stepsDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        noteDaoConfig = daoConfigMap.get(NoteDao.class).clone();
        noteDaoConfig.initIdentityScope(type);

        bookLibDaoConfig = daoConfigMap.get(BookLibDao.class).clone();
        bookLibDaoConfig.initIdentityScope(type);

        studentDaoConfig = daoConfigMap.get(StudentDao.class).clone();
        studentDaoConfig.initIdentityScope(type);
        stepsDaoConfig = daoConfigMap.get(StepsDao.class).clone();
        stepsDaoConfig.initIdentityScope(type);

        noteDao = new NoteDao(noteDaoConfig, this);
        bookLibDao = new BookLibDao(bookLibDaoConfig, this);
        studentDao = new StudentDao(studentDaoConfig, this);
        stepsDao = new StepsDao(stepsDaoConfig, this);

        registerDao(Note.class, noteDao);
        registerDao(BookLib.class, bookLibDao);
        registerDao(Student.class, studentDao);
        registerDao(Steps.class, stepsDao);
    }
    
    public void clear() {
        noteDaoConfig.getIdentityScope().clear();
        bookLibDaoConfig.getIdentityScope().clear();
        studentDaoConfig.getIdentityScope().clear();
        stepsDaoConfig.getIdentityScope().clear();
    }

    public NoteDao getNoteDao() {
        return noteDao;
    }

    public BookLibDao getBookLibDao() {
        return bookLibDao;
    }

    public StudentDao getStudentDao() {
        return studentDao;
    }

    public StepsDao getStepsDao() {
        return stepsDao;
    }
}
