package com.gaia.member.androidlib;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table BOOK_LIB.
 */
public class Steps {

    private Long id;
    private String time;
    private Integer today_step;

    public Steps() {
    }

    public Steps(Long id) {
        this.id = id;
    }

    public Steps(Long id, String time, Integer today_step) {
        this.id = id;
        this.time = time;
        this.today_step = today_step;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getTime() {
        return time;
    }

    public void setTime(String time) {
        this.time = time;
    }

    public Integer getToday_step() {
        return today_step;
    }

    public void setToday_step(Integer today_step) {
        this.today_step = today_step;
    }
}
